const SEARCH_MOVIES = 'SEARCH_MOVIES';
const SEARCH_MOVIES_ERROR = 'SEARCH_MOVIES_ERROR';
const SEARCH_MOVIES_LOADING = 'SEARCH_MOVIES_LOADING';

export { SEARCH_MOVIES, SEARCH_MOVIES_ERROR, SEARCH_MOVIES_LOADING };
